/**
 * LR parser generated by the Syntax tool.
 *
 * https://www.npmjs.com/package/syntax-cli
 *
 *   npm install -g syntax-cli
 *
 *   syntax-cli --help
 *
 * To regenerate run:
 *
 *   syntax-cli \
 *     --grammar ~/path-to-grammar-file \
 *     --mode <parsing-mode> \
 *     --output ~/path-to-output-parser-file.js
 */

'use strict';

/**
 * Matched token text.
 */
let yytext;

/**
 * Length of the matched token text.
 */
let yyleng;

/**
 * Storage object.
 */
let yy = {};

/**
 * Result of semantic action.
 */
let __;

/**
 * Result location object.
 */
let __loc;

function yyloc(start, end) {
  if (!yy.options.captureLocations) {
    return null;
  }

  // Epsilon doesn't produce location.
  if (!start || !end) {
    return start || end;
  }

  return {
    startOffset: start.startOffset,
    endOffset: end.endOffset,
    startLine: start.startLine,
    endLine: end.endLine,
    startColumn: start.startColumn,
    endColumn: end.endColumn,
  };
}

const EOF = '$';

/**
 * List of productions (generated by Syntax tool).
 */
const productions = [[-1,1,(_1) => { __ = _1 }],
[0,0,() => { __ = [] }],
[0,2,(_1,_2) => { _2.unshift(_1); __ = _2 }],
[1,2,(_1,_2) => { __ =  { type : 'rule', identifier : _1, productions : _2 } }],
[2,0,() => { __ = [] }],
[2,2,(_1,_2) => { _2.unshift(_1) ; __ = _2 }],
[3,4,(_1,_2,_3,_4) => { __ = { type : 'production', expansion : _2, term : _4 } }],
[4,0,() => { __ = [] }],
[4,2,(_1,_2) => { _2.unshift(_1) ; __ = _2 }],
[5,1,(_1) => { __ = _1 }],
[5,1,(_1) => { __ = _1 }],
[5,1,(_1) => { __ = _1 }],
[5,1,(_1) => { __ = { type : 'string', value : _1 } }],
[5,1,(_1) => { __ = { type : 'identifier', value : _1 } }],
[6,1,(_1) => { __ = _1 }],
[6,2,(_1,_2) => { __ = { type : 'identifier_arguments', identifier : _1, arguments : _2 } }],
[6,1,(_1) => { __ = { type : 'string', value : _1 } }],
[6,1,(_1) => { __ = { type : 'number', value : _1 } }],
[6,3,(_1,_2,_3) => { __ = { type : 'number_substitution', number : _2, substitution : _3 } }],
[7,0,() => { __ = [] }],
[7,3,(_1,_2,_3) => { __ = _2 }],
[8,0,() => { __ = [] }],
[8,2,(_1,_2) => { _2.unshift(_1); __ = _2 }],
[9,0,() => { __ = [] }],
[9,3,(_1,_2,_3) => { _3.unshift(_2) ; __ = _3 }],
[10,0,() => { __ = [] }],
[10,3,(_1,_2,_3) => { __ = { 'type' : 'substitution', term : _2 } }]];

/**
 * Encoded tokens map.
 */
const tokens = {"IDENTIFIER":"11","SYM_PIPE":"12","SYM_ARROW":"13","KEY_ID":"14","KEY_STRING":"15","KEY_NUM":"16","STRING":"17","KEY_UNDERSCORE":"18","NUMBER":"19","SYM_DOLLAR":"20","SYM_LPAREN":"21","SYM_RPAREN":"22","SYM_COMMA":"23","SYM_LBRACKET":"24","SYM_RBRACKET":"25","$":"26"};

/**
 * Parsing table (generated by Syntax tool).
 */
const table = [{"0":18,"1":1,"11":"s2","26":"r1"},{"0":19,"1":1,"11":"s2","26":"r1"},{"2":20,"3":3,"11":"r4","12":"s4","26":"r4"},{"2":21,"3":3,"11":"r4","12":"s4","26":"r4"},{"4":5,"5":6,"11":"s26","13":"r7","14":"s22","15":"s23","16":"s24","17":"s25"},{"13":"s7"},{"4":37,"5":6,"11":"s26","13":"r7","14":"s22","15":"s23","16":"s24","17":"s25"},{"6":27,"11":"s8","17":"s29","18":"s28","19":"s30","20":"s9"},{"7":31,"11":"r19","12":"r19","21":"s10","22":"r19","23":"r19","25":"r19","26":"r19"},{"19":"s15"},{"6":12,"8":11,"11":"s8","17":"s29","18":"s28","19":"s30","20":"s9","22":"r21"},{"22":"s32"},{"9":33,"22":"r23","23":"s13"},{"6":14,"11":"s8","17":"s29","18":"s28","19":"s30","20":"s9"},{"9":34,"22":"r23","23":"s13"},{"10":35,"11":"r25","12":"r25","22":"r25","23":"r25","24":"s16","25":"r25","26":"r25"},{"6":17,"11":"s8","17":"s29","18":"s28","19":"s30","20":"s9"},{"25":"s36"},{"26":"acc"},{"26":"r2"},{"11":"r3","26":"r3"},{"11":"r5","26":"r5"},{"11":"r9","13":"r9","14":"r9","15":"r9","16":"r9","17":"r9"},{"11":"r10","13":"r10","14":"r10","15":"r10","16":"r10","17":"r10"},{"11":"r11","13":"r11","14":"r11","15":"r11","16":"r11","17":"r11"},{"11":"r12","13":"r12","14":"r12","15":"r12","16":"r12","17":"r12"},{"11":"r13","13":"r13","14":"r13","15":"r13","16":"r13","17":"r13"},{"11":"r6","12":"r6","26":"r6"},{"11":"r14","12":"r14","22":"r14","23":"r14","25":"r14","26":"r14"},{"11":"r16","12":"r16","22":"r16","23":"r16","25":"r16","26":"r16"},{"11":"r17","12":"r17","22":"r17","23":"r17","25":"r17","26":"r17"},{"11":"r15","12":"r15","22":"r15","23":"r15","25":"r15","26":"r15"},{"11":"r20","12":"r20","22":"r20","23":"r20","25":"r20","26":"r20"},{"22":"r22"},{"22":"r24"},{"11":"r18","12":"r18","22":"r18","23":"r18","25":"r18","26":"r18"},{"11":"r26","12":"r26","22":"r26","23":"r26","25":"r26","26":"r26"},{"13":"r8"}];

/**
 * Parsing stack.
 */
const stack = [];

/**
 * Tokenizer instance.
 */
let tokenizer;
/**
 * Generic tokenizer used by the parser in the Syntax tool.
 *
 * https://www.npmjs.com/package/syntax-cli
 *
 * See `--custom-tokinzer` to skip this generation, and use a custom one.
 */

const lexRules = [[/^\/\/.*/, function() { /* skip comments */ }],
[/^\/\*(.|\s)*?\*\//, function() { /* skip comments */ }],
[/^\s+/, function() { /* skip whitespace */ }],
[/^\_/, function() { return 'KEY_UNDERSCORE' }],
[/^\ID/, function() { return 'KEY_ID' }],
[/^\STRING/, function() { return 'KEY_STRING' }],
[/^\NUM/, function() { return 'KEY_NUM' }],
[/^\=>/, function() { return 'SYM_ARROW' }],
[/^\|/, function() { return 'SYM_PIPE' }],
[/^\$/, function() { return 'SYM_DOLLAR' }],
[/^\(/, function() { return 'SYM_LPAREN' }],
[/^\)/, function() { return 'SYM_RPAREN' }],
[/^\[/, function() { return 'SYM_LBRACKET' }],
[/^\]/, function() { return 'SYM_RBRACKET' }],
[/^,/, function() { return 'SYM_COMMA' }],
[/^(\d+(\.\d+)?)/, function() { return 'NUMBER' }],
[/^"[^"]*"/, function() { yytext = yytext.slice(1, -1); return 'STRING'; }],
[/^'[^']*'/, function() { yytext = yytext.slice(1, -1); return 'STRING'; }],
[/^[a-zA-Z0-9_]+/, function() { return 'IDENTIFIER' }]];
const lexRulesByConditions = {"INITIAL":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]};

const EOF_TOKEN = {
  type: EOF,
  value: '',
};

tokenizer = {
  initString(string) {
    this._string = string;
    this._cursor = 0;

    this._states = ['INITIAL'];
    this._tokensQueue = [];

    this._currentLine = 1;
    this._currentColumn = 0;
    this._currentLineBeginOffset = 0;

    /**
     * Matched token location data.
     */
    this._tokenStartOffset = 0;
    this._tokenEndOffset = 0;
    this._tokenStartLine = 1;
    this._tokenEndLine = 1;
    this._tokenStartColumn = 0;
    this._tokenEndColumn = 0;

    return this;
  },

  /**
   * Returns tokenizer states.
   */
  getStates() {
    return this._states;
  },

  getCurrentState() {
    return this._states[this._states.length - 1];
  },

  pushState(state) {
    this._states.push(state);
  },

  begin(state) {
    this.pushState(state);
  },

  popState() {
    if (this._states.length > 1) {
      return this._states.pop();
    }
    return this._states[0];
  },

  getNextToken() {
    // Something was queued, return it.
    if (this._tokensQueue.length > 0) {
      return this._toToken(this._tokensQueue.shift());
    }

    if (!this.hasMoreTokens()) {
      return EOF_TOKEN;
    }

    let string = this._string.slice(this._cursor);
    let lexRulesForState = lexRulesByConditions[this.getCurrentState()];

    for (let i = 0; i < lexRulesForState.length; i++) {
      let lexRuleIndex = lexRulesForState[i];
      let lexRule = lexRules[lexRuleIndex];

      let matched = this._match(string, lexRule[0]);

      // Manual handling of EOF token (the end of string). Return it
      // as `EOF` symbol.
      if (string === '' && matched === '') {
        this._cursor++;
      }

      if (matched !== null) {
        yytext = matched;
        yyleng = yytext.length;
        let token = lexRule[1].call(this);

        if (!token) {
          return this.getNextToken();
        }

        // If multiple tokens are returned, save them to return
        // on next `getNextToken` call.

        if (Array.isArray(token)) {
          const tokensToQueue = token.slice(1);
          token = token[0];
          if (tokensToQueue.length > 0) {
            this._tokensQueue.unshift(...tokensToQueue);
          }
        }

        return this._toToken(token, yytext);
      }
    }

    if (this.isEOF()) {
      this._cursor++;
      return EOF_TOKEN;
    }

    this.throwUnexpectedToken(
      string[0],
      this._currentLine,
      this._currentColumn
    );
  },

  /**
   * Throws default "Unexpected token" exception, showing the actual
   * line from the source, pointing with the ^ marker to the bad token.
   * In addition, shows `line:column` location.
   */
  throwUnexpectedToken(symbol, line, column) {
    const lineSource = this._string.split('\n')[line - 1];
    let lineData = '';

    if (lineSource) {
      const pad = ' '.repeat(column);
      lineData = '\n\n' + lineSource + '\n' + pad + '^\n';
    }

    throw new SyntaxError(
      `${lineData}Unexpected token: "${symbol}" ` +
      `at ${line}:${column}.`
    );
  },

  getCursor() {
    return this._cursor;
  },

  getCurrentLine() {
    return this._currentLine;
  },

  getCurrentColumn() {
    return this._currentColumn;
  },

  _captureLocation(matched) {
    const nlRe = /\n/g;

    // Absolute offsets.
    this._tokenStartOffset = this._cursor;

    // Line-based locations, start.
    this._tokenStartLine = this._currentLine;
    this._tokenStartColumn =
      this._tokenStartOffset - this._currentLineBeginOffset;

    // Extract `\n` in the matched token.
    let nlMatch;
    while ((nlMatch = nlRe.exec(matched)) !== null) {
      this._currentLine++;
      this._currentLineBeginOffset = this._tokenStartOffset + nlMatch.index + 1;
    }

    this._tokenEndOffset = this._cursor + matched.length;

    // Line-based locations, end.
    this._tokenEndLine = this._currentLine;
    this._tokenEndColumn = this._currentColumn =
      (this._tokenEndOffset - this._currentLineBeginOffset);
  },

  _toToken(tokenType, yytext = '') {
    return {
      // Basic data.
      type: tokenType,
      value: yytext,

      // Location data.
      startOffset: this._tokenStartOffset,
      endOffset: this._tokenEndOffset,
      startLine: this._tokenStartLine,
      endLine: this._tokenEndLine,
      startColumn: this._tokenStartColumn,
      endColumn: this._tokenEndColumn,
    };
  },

  isEOF() {
    return this._cursor === this._string.length;
  },

  hasMoreTokens() {
    return this._cursor <= this._string.length;
  },

  _match(string, regexp) {
    let matched = string.match(regexp);
    if (matched) {
      // Handle `\n` in the matched token to track line numbers.
      this._captureLocation(matched[0]);
      this._cursor += matched[0].length;
      return matched[0];
    }
    return null;
  },
};

/**
 * Expose tokenizer so it can be accessed in semantic actions.
 */
yy.lexer = tokenizer;
yy.tokenizer = tokenizer;

/**
 * Global parsing options. Some options can be shadowed per
 * each `parse` call, if the optations are passed.
 *
 * Initalized to the `captureLocations` which is passed
 * from the generator. Other options can be added at runtime.
 */
yy.options = {
  captureLocations: false,
};

/**
 * Parsing module.
 */
const yyparse = {
  /**
   * Sets global parsing options.
   */
  setOptions(options) {
    yy.options = options;
    return this;
  },

  /**
   * Returns parsing options.
   */
  getOptions() {
    return yy.options;
  },

  /**
   * Parses a string.
   */
  parse(string, parseOptions) {
    if (!tokenizer) {
      throw new Error(`Tokenizer instance wasn't specified.`);
    }

    tokenizer.initString(string);

    /**
     * If parse options are passed, override global parse options for
     * this call, and later restore global options.
     */
    let globalOptions = yy.options;
    if (parseOptions) {
      yy.options = Object.assign({}, yy.options, parseOptions);
    }

    /**
     * Allow callers to do setup work based on the
     * parsing string, and passed options.
     */
    yyparse.onParseBegin(string, tokenizer, yy.options);

    stack.length = 0;
    stack.push(0);

    let token = tokenizer.getNextToken();
    let shiftedToken = null;

    do {
      if (!token) {
        // Restore options.
        yy.options = globalOptions;
        unexpectedEndOfInput();
      }

      let state = stack[stack.length - 1];
      let column = tokens[token.type];

      if (!table[state].hasOwnProperty(column)) {
        yy.options = globalOptions;
        unexpectedToken(token);
      }

      let entry = table[state][column];

      // Shift action.
      if (entry[0] === 's') {
        let loc = null;

        if (yy.options.captureLocations) {
          loc = {
            startOffset: token.startOffset,
            endOffset: token.endOffset,
            startLine: token.startLine,
            endLine: token.endLine,
            startColumn: token.startColumn,
            endColumn: token.endColumn,
          };
        }

        stack.push(
          {symbol: tokens[token.type], semanticValue: token.value, loc},
          Number(entry.slice(1))
        );
        shiftedToken = token;
        token = tokenizer.getNextToken();
      }

      // Reduce action.
      else if (entry[0] === 'r') {
        let productionNumber = entry.slice(1);
        let production = productions[productionNumber];
        let hasSemanticAction = typeof production[2] === 'function';
        let semanticValueArgs = hasSemanticAction ? [] : null;

        const locationArgs = (
          hasSemanticAction && yy.options.captureLocations
            ? []
            : null
        );

        if (production[1] !== 0) {
          let rhsLength = production[1];
          while (rhsLength-- > 0) {
            stack.pop();
            let stackEntry = stack.pop();

            if (hasSemanticAction) {
              semanticValueArgs.unshift(stackEntry.semanticValue);

              if (locationArgs) {
                locationArgs.unshift(stackEntry.loc);
              }
            }
          }
        }

        const reduceStackEntry = {symbol: production[0]};

        if (hasSemanticAction) {
          yytext = shiftedToken ? shiftedToken.value : null;
          yyleng = shiftedToken ? shiftedToken.value.length : null;

          const semanticActionArgs = (
            locationArgs !== null
              ? semanticValueArgs.concat(locationArgs)
              : semanticValueArgs
          );

          production[2](...semanticActionArgs);

          reduceStackEntry.semanticValue = __;

          if (locationArgs) {
            reduceStackEntry.loc = __loc;
          }
        }

        const nextState = stack[stack.length - 1];
        const symbolToReduceWith = production[0];

        stack.push(
          reduceStackEntry,
          table[nextState][symbolToReduceWith]
        );
      }

      // Accept.
      else if (entry === 'acc') {
        stack.pop();
        let parsed = stack.pop();

        if (stack.length !== 1 ||
            stack[0] !== 0 ||
            tokenizer.hasMoreTokens()) {
          // Restore options.
          yy.options = globalOptions;
          unexpectedToken(token);
        }

        if (parsed.hasOwnProperty('semanticValue')) {
          yy.options = globalOptions;
          yyparse.onParseEnd(parsed.semanticValue);
          return parsed.semanticValue;
        }

        yyparse.onParseEnd();

        // Restore options.
        yy.options = globalOptions;
        return true;
      }

    } while (tokenizer.hasMoreTokens() || stack.length > 1);
  },

  setTokenizer(customTokenizer) {
    tokenizer = customTokenizer;
    return yyparse;
  },

  getTokenizer() {
    return tokenizer;
  },

  onParseBegin(string, tokenizer, options) {},
  onParseEnd(parsed) {},
};


    // Can be "require" statments, or direct declarations.
  

function unexpectedToken(token) {
  if (token.type === EOF) {
    unexpectedEndOfInput();
  }

  tokenizer.throwUnexpectedToken(
    token.value,
    token.startLine,
    token.startColumn
  );
}

function unexpectedEndOfInput() {
  parseError(`Unexpected end of input.`);
}

function parseError(message) {
  throw new SyntaxError(message);
}

module.exports = yyparse;
